Repository kvlsndkf/project, pull requests merged in 2022-06, with the labels that each got.

#47 Bug update etecs
  classes/schools/School.class.php
Labels: CODE REVIEW

#41 Modais das Matérias
  private/adm/pages/js/delete-subject.js
  private/adm/pages/register/register-subject/form-batch-registration.subject.controller.php
  private/adm/pages/register/register-subject/form-register-subject.page.php
  private/adm/pages/register/register-subject/form-update-subject.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
  private/adm/pages/register/register-teacher/form-update-teacher.page.php
  private/adm/pages/register/upload/courses/629650fc408f7.png
  private/adm/pages/register/upload/schools/629650a89abe2.jpg
  private/adm/pages/register/upload/teachers/629407b69c738.png
  private/adm/pages/register/upload/teachers/629650182ff27.png
  private/style/form-register-teacher.page.css
  private/style/form-update-teacher.style.css
Labels: CODE REVIEW, Front pronto

#51 feat/style-edit-school
  private/adm/pages/register/register-school/form-register-school.page.php
  private/adm/pages/register/register-school/form-update-school.page.php
  private/adm/pages/register/upload/courses/62961061c1a95.png
  private/adm/pages/register/upload/courses/6296107d5f2ca.png
  private/adm/pages/register/upload/courses/62961094544ad.png
  private/adm/pages/register/upload/courses/629610afb4c70.png
  private/adm/pages/register/upload/courses/6296156800cfc.png
  private/adm/pages/register/upload/courses/6296157f15931.png
  private/adm/pages/register/upload/courses/6296159ac7f6c.png
  private/adm/pages/register/upload/courses/629618a2a4c87.png
  private/adm/pages/register/upload/courses/629619089cec4.png
  private/adm/pages/register/upload/courses/6296192062850.jpg
  private/adm/pages/register/upload/courses/62962157cbe15.png
  private/adm/pages/register/upload/courses/629621d6b3506.png
  private/adm/pages/register/upload/courses/629621ed0e3c2.png
  private/adm/pages/register/upload/courses/62965b6ad3ef4.jpg
  private/adm/pages/register/upload/courses/62965b862ca05.jpg
  private/adm/pages/register/upload/courses/62965ba5c53c7.jpg
  private/adm/pages/register/upload/schools/62961537b15cb.png
  private/adm/pages/register/upload/schools/6296188946b11.png
  private/adm/pages/register/upload/schools/62962137cb537.png
  private/adm/pages/register/upload/schools/629659bc77165.jpg
  private/adm/pages/register/upload/schools/6296c54209197.jpg
  private/adm/pages/register/upload/schools/6296c60c253aa.jpg
  private/adm/pages/register/upload/schools/6296c9e708a2d.png
  private/adm/pages/register/upload/teachers/629614d746704.png
  private/adm/pages/register/upload/teachers/629614dfd69cf.png
  private/adm/pages/register/upload/teachers/629614e9e17ce.png
  private/adm/pages/register/upload/teachers/62961808b20b0.png
  private/adm/pages/register/upload/teachers/6296181230ba5.png
  private/adm/pages/register/upload/teachers/6296182218887.png
  private/adm/pages/register/upload/teachers/629620e401a06.png
  private/adm/pages/register/upload/teachers/629620ea972a9.png
  private/adm/pages/register/upload/teachers/629620eedd729.png
  private/adm/pages/register/upload/teachers/6296589447916.jpg
  private/style/form-register-teacher.page.css
  private/style/form-update-teacher.style.css
  views/pages/register/upload/student/629615d272692.png
  views/pages/register/upload/student/629619acaa583.png
  views/pages/register/upload/student/629622c2f0fe3.png
  views/pages/register/upload/student/62962454effd0.png
Labels: CODE REVIEW, Front pronto

#53 Ajuste na posiçaõ da paginação
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
  private/style/button-delete-course.style.css
Labels: CODE REVIEW

#54 Paginação das listagens do modal do curso
  classes/schools/Course.class.php
  private/adm/pages/js/pagination-modal-course-schools.js
  private/adm/pages/js/pagination-modal-course-subjects.js
  private/adm/pages/js/pagination-modal-course-teachers.js
  private/adm/pages/register/register-course/controller/pagination-modal-course-schools.php
  private/adm/pages/register/register-course/controller/pagination-modal-course-subjects.php
  private/adm/pages/register/register-course/controller/pagination-modal-course-teachers.php
  private/adm/pages/register/register-course/list-course.page.php
Labels: CODE REVIEW, Back pronto

#48 Modal Sobre as ETECs
  private/adm/pages/js/pagination-teacher-modal.js
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/upload/courses/6298e9ea17092.jpg
  private/adm/pages/register/upload/schools/62965c54dc67b.jpg
  private/adm/pages/register/upload/schools/6296755fbdc4d.jpg
  private/adm/pages/register/upload/schools/62981805348f0.png
  private/adm/pages/register/upload/schools/629bbe861ae16.jpg
  private/adm/pages/register/upload/teachers/6296d74b75c33.jpg
  private/adm/pages/register/upload/teachers/6296d751c8f96.jpg
  private/style/modal-about.style.css
  views/images/components/location-icon.svg
  views/images/components/x-button.svg
Labels: CODE REVIEW, Front pronto

#55 Feat/list message
  classes/messages/Message.class.php
  private/adm/pages/dashboard/dashboard.page.php
  private/adm/pages/message/controller/read-message.controller.php
  private/adm/pages/message/list-message.page.php
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/registration panel/registration-panel-page.php
  private/adm/pages/register/upload/courses/628aea38d483e.jpg
  private/adm/pages/register/upload/courses/6292857f4ae7f.png
  private/adm/pages/register/upload/courses/62928897afec0.png
  private/adm/pages/register/upload/courses/629288e9e2855.png
  private/adm/pages/register/upload/courses/62929447c9aa8.png
  private/adm/pages/register/upload/courses/6292afac5a43f.png
  private/adm/pages/register/upload/courses/6293f10a45b7d.jpg
  private/adm/pages/register/upload/schools/6285bb3914ad6.jpg
  private/adm/pages/register/upload/schools/6285bb84c8c1d.jpg
  private/adm/pages/register/upload/schools/6285bc1e6aab9.jpg
  private/adm/pages/register/upload/schools/6286d9686bcee.jpg
  private/adm/pages/register/upload/schools/6286dc80167f5.jpg
  private/adm/pages/register/upload/schools/6286ddf3c9147.jpg
  private/adm/pages/register/upload/schools/6286dec0decc5.jpg
  private/adm/pages/register/upload/schools/6289326403ad8.jpg
  private/adm/pages/register/upload/schools/6289a3e42db76.jpg
  private/adm/pages/register/upload/schools/628c3b1dc6fe1.jpg
  private/adm/pages/register/upload/schools/629293b4e5be0.jpg
  private/adm/pages/register/upload/schools/6293f0e817a1a.png
  private/adm/pages/register/upload/teachers/627c64683f62f.png
  private/adm/pages/register/upload/teachers/627c6a56e7698.jpg
  private/adm/pages/register/upload/teachers/62843e6984684.jpg
  private/adm/pages/register/upload/teachers/62843e87cf332.jpg
  private/adm/pages/register/upload/teachers/62843ea3baefb.jpg
  private/adm/pages/register/upload/teachers/62843ec655fae.jpg
  private/adm/pages/register/upload/teachers/62843ee557b3b.jpg
  private/adm/pages/register/upload/teachers/62843efa9d0f4.jpg
  private/adm/pages/register/upload/teachers/62843f0dc790d.jpg
  private/adm/pages/register/upload/teachers/62843f22acb85.jpg
  private/adm/pages/register/upload/teachers/62843f3343fc9.jpg
  private/adm/pages/register/upload/teachers/62843f44ba04d.jpg
  private/adm/pages/register/upload/teachers/62843ff141788.jpg
  private/adm/pages/register/upload/teachers/6284400da20f5.jpg
  private/adm/pages/register/upload/teachers/62844046e707d.jpg
  private/adm/pages/register/upload/teachers/628440a302432.jpg
  private/adm/pages/register/upload/teachers/6284417bbbcaa.jpg
  private/adm/pages/register/upload/teachers/628931fd99c73.jpg
  private/adm/pages/register/upload/teachers/6289a3afdaad5.jpg
  private/adm/pages/register/upload/teachers/62929343c01eb.jpg
  private/adm/pages/register/upload/teachers/6293f001e8d69.jpg
  views/pages/register/upload/student/629369b09008e.png
  views/pages/register/upload/student/62936cbc0a680.png
  views/pages/register/upload/student/62936d7761431.png
  views/pages/register/upload/student/6294d8451784e.png
  views/pages/register/upload/student/teste.txt
Labels: CODE REVIEW, Back pronto

#56 Fix/Hover no Botão de sair
  private/adm/pages/dashboard/dashboard.page.php
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/register.styles.css
  private/adm/pages/register/registration panel/registration-panel-page.php
Labels: CODE REVIEW, Front pronto

#52 feat/style-register-course
  private/adm/pages/register/register-course/form-register-course.page.php
  private/adm/pages/register/register-school/form-register-school.page.php
  private/student/pages/question/upload/docs/629c269e92a15.xml
  private/style/form-register-teacher.page.css
Labels: CODE REVIEW, Front pronto, WAITING

#58 feat/style-update-course
  private/adm/pages/register/register-course/form-update-course.page.php
  private/adm/pages/register/register-school/form-update-school.page.php
Labels: CODE REVIEW, Front pronto

#62 Style register student
  private/adm/pages/register/register-course/form-register-course.page.php
  private/adm/pages/register/register-module/form-register-module.page.php
  private/adm/pages/register/register-module/form-update-module.page.php
  private/adm/pages/register/register-school/form-register-school.page.php
  private/adm/pages/register/register-school/form-update-school.page.php
  private/adm/pages/register/register-subject/form-register-subject.page.php
  private/adm/pages/register/register-subject/form-update-subject.page.php
  private/adm/pages/register/register-teacher/form-register-teacher.page.php
  private/adm/pages/register/register-teacher/form-update-teacher.page.php
  views/js/password-visibility.js
  views/js/register-student.js
  views/pages/register/image/background/bg-stars.svg
  views/pages/register/image/components/hide-pass.svg
  views/pages/register/image/components/show-pass.svg
  views/pages/register/register-student/register-student.style.css
  views/pages/register/register-student/step1-register-student.page.php
  views/pages/register/register-student/step2-register-student.page.php
  views/pages/register/register-student/step3-register-student.page.php
  views/pages/register/register-student/step4-register-student.page.php
  views/styles/colors.style.css
  views/styles/fonts.style.css
Labels: CODE REVIEW, Front pronto

#59 Modal Sobre dos Cursos
  classes/schools/Course.class.php
  private/adm/images/icons/icon-local.svg
  private/adm/pages/js/pagination-modal-course-schools.js
  private/adm/pages/js/pagination-modal-course-subjects.js
  private/adm/pages/js/pagination-modal-course-teachers.js
  private/adm/pages/js/pagination-teacher-modal.js
  private/adm/pages/register/register-course/controller/pagination-modal-course-schools.php
  private/adm/pages/register/register-course/controller/pagination-modal-course-subjects.php
  private/adm/pages/register/register-course/controller/pagination-modal-course-teachers.php
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-school/controller/pagination-teacher-modal.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register.styles.css
  private/style/modal-about.style.css
Labels: CODE REVIEW, Front pronto

#65 Fix/estilo modal fale conosco
  views/landing-page/fale-conosco.css
  views/landing-page/landing-page.php
  views/pages/login/validacao.js
Labels: CODE REVIEW, Front pronto

#64 Página do Fale Conosco
  private/adm/pages/dashboard/dashboard.page.php
  private/adm/pages/message/list-message.page.php
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/register.styles.css
  private/adm/pages/register/registration panel/registration-panel-page.php
  views/images/components/fale-conosco-current.svg
Labels: CODE REVIEW, Front pronto

#66 Fix/eye opened login
  views/pages/login/css-login/login-style.css
  views/pages/login/css-login/valid-login.css
  views/pages/login/login-page.php
  views/pages/login/validacao.js
Labels: CODE REVIEW, Front pronto

#67 Fix do Texto no Modal das ETECs
  private/adm/pages/register/register-school/list-school.page.php
  private/style/modal-about.style.css
Labels: CODE REVIEW, Front pronto

#71 Feat/sessao-video-pitch
  views/landing-page/img/perfil.svg
  views/landing-page/landing-page-styles.css
  views/landing-page/landing-page.php
Labels: CODE REVIEW, Front pronto

#72 Feat/border-video
  views/landing-page/landing-page-styles.css
Labels: CODE REVIEW, Front em andamento

#69 Estilo do Feed
  private/student/pages/answer-question/upload/docs/62a9e5b6dbc06.docx
  private/student/pages/home/home.page.php
  private/student/pages/question/upload/docs/62a9dcbc92c71.docx
  private/student/pages/question/upload/docs/62a9f9b483cb1.docx
  private/student/style/feed.style.css
  views/images/background/feed/pedir-heelp-background.svg
  views/images/components/denunciar-icon.svg
  views/images/components/download-icon.svg
  views/images/components/file-icon.svg
  views/images/components/following-icon.svg
  views/images/components/link-icon.svg
  views/images/components/notifications-icon.svg
  views/images/components/pedir-heelp-flipper.svg
  views/images/components/profile-icon.svg
  views/images/components/star-icon.svg
  views/images/components/upper-line.svg
Labels: CODE REVIEW, Front pronto

#76 Correção da Home
  private/student/pages/home/home.page.php
  private/student/styles/feed.style.css
  views/images/background/feed/pedir-heelp-background.svg
  views/images/components/denunciar-icon.svg
  views/images/components/download-icon.svg
  views/images/components/file-icon.svg
  views/images/components/following-icon.svg
  views/images/components/link-icon.svg
  views/images/components/notifications-icon.svg
  views/images/components/pedir-heelp-flipper.svg
  views/images/components/profile-icon.svg
  views/images/components/star-icon.svg
  views/images/components/upper-line.svg
Labels: CODE REVIEW, Front pronto

#73 Perfil do aluno
  classes/answers/Answer.class.php
  classes/questions/Question.class.php
  classes/schools/Module.class.php
  classes/users/Student.class.php
  classes/users/StudentMethods.class.php
  private/student/pages/detail-perfil-student/controller/update-perfil-student.controller.php
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
  private/student/pages/detail-perfil-student/update-perfil-student.page.php
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/home/home.page.php
Labels: CODE REVIEW, Back pronto

#74 Estilização da página de pergunta
  private/student/pages/question/question.page.php
  private/student/pages/question/upload/docs/62ab3a76d173b.docx
  views/pages/register/register-student/register-student.style.css
  views/styles/colors.style.css
Labels: CODE REVIEW, Front pronto

#77 Estilo dos Detalhes das Perguntas
  private/student/pages/answer-question/upload/docs/62ac7ffe3daa0.docx
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/detail-question/style/avaliation.style.css
  private/student/pages/home/home.page.php
  private/student/pages/question/upload/docs/62aceb0be9215.docx
  private/student/styles/feed.style.css
  views/images/components/logout-icon.svg
  views/images/components/settings-icon.svg
Labels: CODE REVIEW, Front pronto

#78 Seguir/Deixar de seguir alunos
  classes/followers/Follow.class.php
  database/script/help.sql
  database/script/script.txt
  private/student/pages/detail-perfil-student/controller/follow-user.controller.php
  private/student/pages/detail-perfil-student/controller/list-followers-user.controller.php
  private/student/pages/detail-perfil-student/controller/list-following.controller.php
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
  private/student/pages/detail-perfil-student/list-followers-student.page.php
  private/student/pages/detail-perfil-student/list-following-student.page.php
Labels: CODE REVIEW, Back pronto

#79 Perfil das Escolas
  classes/schools/School.class.php
  classes/schools/Teacher.class.php
  private/school/school-profile.page.php
Labels: CODE REVIEW, Back pronto

#81 Pesquisa no Heelp!
  classes/answers/Answer.class.php
  classes/researches/Search.class.php
  classes/schools/School.class.php
  database/script/help.sql
  database/script/script.txt
  private/school/school-profile.page.php
  private/student/images/not-found.svg
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/home/home.page.php
  private/student/pages/search/search.page.php
Labels: CODE REVIEW, Back pronto

#85 Preferências
  classes/preferences/Preference.class.php
  classes/questions/Question.class.php
  classes/schools/School.class.php
  private/school/school-profile.page.php
  private/student/images/no-preferences.svg
  private/student/pages/home/home.page.php
  private/student/pages/preferences/preference.page.php
  private/student/pages/search/search.page.php
Labels: CODE REVIEW, Back pronto

#82 Fix: colocar seta de voltar na pergunta
  private/student/pages/question/question.page.php
  views/pages/register/register-student/register-student.style.css
Labels: CODE REVIEW, Front pronto

#84 Estilização do Perfil do Aluno
  private/student/pages/answer-question/upload/docs/62af9647e721d.docx
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/home/home.page.php
  private/student/pages/question/upload/docs/62ad248649439.docx
  private/student/pages/question/upload/docs/62ae6650a4b60.docx
  private/student/pages/question/upload/docs/62ae668800ec4.docx
  private/student/pages/question/upload/docs/62ae6a368c4f8.docx
  private/student/pages/question/upload/docs/62af91ad37443.docx
  private/student/pages/question/upload/docs/62af91b8da9fa.docx
  private/student/pages/question/upload/docs/62af91cfc555b.docx
  private/student/pages/question/upload/docs/62af91da0e6a6.docx
  private/student/pages/question/upload/docs/62af91e6222f8.docx
  private/student/pages/question/upload/docs/62af91f2d5f02.docx
  private/student/styles/feed.style.css
  views/images/components/date-range.svg
Labels: CODE REVIEW, Front pronto

#80 Estilização da resposta
  private/student/pages/answer-question/answer-question.page.php
  private/student/pages/answer-question/answer-question.style.css
  private/student/pages/answer-question/images/arrow-back-mod.svg
  private/student/pages/answer-question/images/blue-logo.svg
  views/pages/register/register-student/register-student.style.css
  views/styles/button.style.css
  views/styles/colors.style.css
  views/styles/input.style.css
Labels: CODE REVIEW, Front pronto

#87 Feat/Modal-Geral
  private/student/js/delete-answer-question.js
  private/student/js/delete-question.js
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/home/home.page.php
  private/student/pages/home/modal.css
  views/styles/style.global.css
Labels: CODE REVIEW, Front pronto

#88 Ranking 1
  classes/rankings/Ranking.class.php
  private/student/images/icons/bronze.svg
  private/student/images/icons/gold.svg
  private/student/images/icons/silver.svg
  private/student/pages/home/home.page.php
Labels: CODE REVIEW, Back pronto

#92 Feed de seguidores
  classes/feed/Following.class.php
  classes/researches/Search.class.php
  private/student/pages/feed-following/feed-following.page.php
  private/student/pages/home/home.page.php
Labels: CODE REVIEW, Back pronto

#90 Feat/ajuste-cor-modal
  private/student/js/delete-answer-question.js
  private/student/pages/home/home.page.php
  private/student/pages/home/modal.css
Labels: CODE REVIEW, Front pronto

#89 Estilo do Perfil das ETECs
  private/school/school-profile.page.php
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/home/home.page.php
  private/student/styles/feed.style.css
  private/style/modal-about.style.css
  views/images/components/trophy-primary.svg
Labels: CODE REVIEW, Front pronto

#86 Estilização pesquisa
  classes/researches/Search.class.php
  private/student/pages/search/search.page.php
  private/student/pages/search/style.search.css
  private/student/styles/feed.style.css
  views/styles/colors.style.css
Labels: CODE REVIEW, Front pronto

#94 Estilo de Seguindo e Seguidores
  private/student/pages/detail-perfil-student/list-followers-student.page.php
  private/student/pages/detail-perfil-student/list-following-student.page.php
  private/student/styles/feed.style.css
Labels: CODE REVIEW, Front pronto

#97 Solicitação de informação
  views/pages/register/register-student/step2-register-student.page.php
Labels: CODE REVIEW, Back pronto

#96 Página de denúncia
  classes/answers/Answer.class.php
  classes/denunciations/Denunciation.class.php
  classes/questions/Question.class.php
  classes/users/StudentMethods.class.php
  database/script/help.sql
  database/script/script.txt
  private/adm/pages/dashboard/dashboard.page.php
  private/adm/pages/denunciation/controller/analysis-denunciation.controller.php
  private/adm/pages/denunciation/controller/getContexts.controller.php
  private/adm/pages/denunciation/controller/resolve-denunciation.controller.php
  private/adm/pages/denunciation/detail-profile-student/detail-profile-student.page.php
  private/adm/pages/denunciation/detail-question/detail-question.page.php
  private/adm/pages/denunciation/list-denunciation.page.php
  private/adm/pages/message/list-message.page.php
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/registration panel/registration-panel-page.php
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
Labels: CODE REVIEW, Back pronto

#93 Style preferences
  classes/denunciations/Denunciation.class.php
  private/student/pages/home/home.page.php
  private/student/pages/preferences/controller/denunciation-preference.controller.php
  private/student/pages/preferences/preference.page.php
  private/student/pages/search/search.page.php
  private/student/pages/search/style.search.css
  private/student/styles/feed.style.css
Labels: CODE REVIEW, Front pronto

#102 Index e Modal de Solicitação
  index.php
  private/logout/logout.controller.php
  views/landing-page/landing-page.php
  views/pages/login/login-page.php
  views/pages/register/register-student/step2-register-student.page.php
Labels: CODE REVIEW, Front pronto

#101 Ajuste de atualização de senha e formatação de hora
  classes/users/Student.class.php
  classes/users/StudentMethods.class.php
  private/adm/pages/register/register-school/list-school.page.php
  private/student/pages/detail-perfil-student/controller/update-perfil-student.controller.php
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
Labels: CODE REVIEW, Back pronto

#99 Dashboard
  classes/dashboard/Dashboard.class.php
  private/adm/pages/dashboard/dashboard.page.php
Labels: CODE REVIEW, Back pronto

#106 Etec sem conta
  classes/schools/Course.class.php
  classes/schools/School.class.php
Labels: CODE REVIEW, Back pronto

#107 Confirmação de email localmente
  classes/users/Student.class.php
Labels: CODE REVIEW, Back pronto

#105 Reparos no Heelp!
  classes/messages/Message.class.php
  classes/rankings/Ranking.class.php
  classes/researches/Search.class.php
  classes/schools/School.class.php
  private/logout/logout.controller.php
  private/school/school-profile.page.php
  private/student/images/no-post-following.svg
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
  private/student/pages/detail-perfil-student/list-followers-student.page.php
  private/student/pages/detail-perfil-student/list-following-student.page.php
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/feed-following/feed-following.page.php
  private/student/pages/home/home.page.php
  private/student/pages/preferences/preference.page.php
  private/student/pages/search/search.page.php
Labels: CODE REVIEW, Back pronto

#110 Listagem de usuários no admistrador
  classes/users/StudentController.class.php
  private/adm/pages/dashboard/dashboard.page.php
  private/adm/pages/list-profiles/controller/block-student.controller.php
  private/adm/pages/list-profiles/controller/unlock-student.controller.php
  private/adm/pages/list-profiles/list-profiles.page.php
Labels: CODE REVIEW, Back pronto

#108 Reparos Gerais
  index.php
  private/school/school-profile.page.php
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
  private/student/pages/detail-perfil-student/list-followers-student.page.php
  private/student/pages/detail-perfil-student/list-following-student.page.php
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/feed-following/feed-following.page.php
  private/student/pages/home/home.page.php
  private/student/pages/preferences/preference.page.php
  private/student/pages/search/search.page.php
  private/student/styles/feed.style.css
Labels: CODE REVIEW, Front pronto

#109 Reparos da Landing Page
  index.php
  private/adm/pages/dashboard/dashboard.page.php
  private/adm/pages/dashboard/style.dashboard.css
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register.styles.css
  private/style/modal-about.style.css
  views/landing-page/landing-page-styles.css
  views/pages/register/register-profile/register-profile.pages.php
  views/pages/register/register-student/step3-register-student.page.php
Labels: CODE REVIEW, Front pronto

#104 Style denunciations
  .vscode/extensions.json
  classes/denunciations/Denunciation.class.php
  private/adm/images/components/icon-denunciation.svg
  private/adm/pages/dashboard/dashboard.page.php
  private/adm/pages/denunciation/detail-profile-student/detail-profile-student.page.php
  private/adm/pages/denunciation/detail-question/detail-question.page.php
  private/adm/pages/denunciation/list-denunciation.page.php
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/registration panel/registration-panel-page.php
  private/student/styles/list-denunciation.styles.css
  private/style/list-denunciation.styles.css
  views/styles/button.style.css
  views/styles/colors.style.css
  views/styles/font-format.style.css
Labels: CODE REVIEW, Front pronto, WAITING

#91 Feat/editar-perfil-aluno
  private/student/pages/detail-perfil-student/controller/update-perfil-student.controller.php
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
  private/student/pages/detail-perfil-student/list-followers-student.page.php
  private/student/pages/detail-perfil-student/list-following-student.page.php
  private/student/pages/detail-perfil-student/update-perfil-student.page.php
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/home/home.page.php
  private/student/styles/feed.style.css
  private/style/update-profile-student.css
  views/images/components/seta-accordion.svg
Labels: CODE REVIEW, Front pronto

#114 Ajustes HEELP
  private/adm/pages/denunciation/detail-question/detail-question.page.php
  private/student/pages/detail-perfil-student/update-perfil-student.page.php
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/feed-following/feed-following.page.php
  private/student/pages/home/home.page.php
  private/student/pages/preferences/preference.page.php
Labels: CODE REVIEW, Front pronto

#116 Ajuste feed filtrado
  classes/questions/Question.class.php
Labels: CODE REVIEW

#113 Regras de denúncia
  classes/answers/Answer.class.php
  classes/denunciations/Denunciation.class.php
  classes/feed/Following.class.php
  classes/preferences/Preference.class.php
  classes/users/StudentController.class.php
  classes/users/StudentMethods.class.php
  database/script/help.sql
  private/adm/pages/denunciation/controller/resolve-denunciation.controller.php
  private/adm/pages/denunciation/list-denunciation.page.php
  private/student/images/profile-blocked.svg
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
Labels: CODE REVIEW

#115 fix ADM and HEELP
  private/adm/pages/dashboard/dashboard.page.php
  private/adm/pages/dashboard/style.dashboard.css
  private/adm/pages/message/list-message.page.php
  private/adm/pages/message/list-message.style.css
  private/student/images/icons/link-icon.svg
  private/student/pages/answer-question/answer-question.page.php
  private/student/pages/answer-question/answer-question.style.css
  private/student/pages/detail-perfil-student/detail-perfil-student.page.php
  private/student/pages/detail-perfil-student/list-followers-student.page.php
  private/student/pages/detail-perfil-student/list-following-student.page.php
  private/student/pages/detail-perfil-student/update-perfil-student.page.php
  private/student/pages/detail-question/detail-question.page.php
  private/student/pages/home/home.page.php
  private/student/pages/question/question.page.php
  private/student/pages/question/questionUpdate.page.php
  private/student/styles/not-found.styles.css
Labels: CODE REVIEW, Front pronto
