Repository kvlsndkf/project, pull requests merged in 2022-05, with the labels that each got.

#6 Landing Page Heelp!
  views/landing-page/img/Logo-Blue.svg
  views/landing-page/img/Logo-Transparente.svg
  views/landing-page/img/Logo.svg
  views/landing-page/img/background.svg
  views/landing-page/img/botão âncora.svg
  views/landing-page/img/foto1-ajuda.svg
  views/landing-page/img/foto2-networking.svg
  views/landing-page/img/foto3-desafios.svg
  views/landing-page/img/foto4-xp.svg
  views/landing-page/img/foto5-seta-circulo.svg
  views/landing-page/img/foto6-ranking.svg
  views/landing-page/landing-page-styles.css
  views/landing-page/landing-page.php
Labels: CODE REVIEW

#16 Painel de Registro - ADM
  private/adm/pages/register/registration panel/img/course-img.svg
  private/adm/pages/register/registration panel/img/module-img.svg
  private/adm/pages/register/registration panel/img/prof-img.svg
  private/adm/pages/register/registration panel/img/school-img.svg
  private/adm/pages/register/registration panel/img/subject-img.svg
  private/adm/pages/register/registration panel/registration-panel-page.php
  private/adm/pages/register/registration panel/registration-panel-style.css
  private/adm/pages/register/registration panel/registration-panel.php
  views/images/components/dashboard-img.svg
  views/images/components/denuncia-img.svg
  views/images/components/fale-conosco-img.svg
  views/images/components/informacoes-img.svg
  views/images/components/listagem-img.svg
  views/images/components/sair-img.svg
Labels: CODE REVIEW

#15 Feat/register teacher
  private/adm/images/background/bg-stars.svg
  private/adm/images/components/arrow.svg
  private/adm/images/teste.txt
  private/adm/pages/register/image/form-teacher/background/bg-stars.svg
  private/adm/pages/register/image/form-teacher/components/arrow.svg
  private/adm/pages/register/register-teacher/form-register-teacher.page.php
  private/adm/pages/register/upload/teachers/62669f6e9ada7.png
  private/adm/pages/register/upload/teachers/62669f82176b6.png
  private/adm/pages/register/upload/teachers/62669fa6e2f48.png
  private/adm/pages/register/upload/teachers/62669fe178615.png
  private/adm/pages/register/upload/teachers/62669feb29a76.png
  private/adm/pages/register/upload/teachers/62669ff637b6f.png
  private/adm/pages/register/upload/teachers/6266a00d45e3a.png
  private/adm/pages/register/upload/teachers/6266a01a24101.png
  private/adm/pages/register/upload/teachers/6266a02a9a3f1.png
  private/adm/pages/register/upload/teachers/6279b89fc3c4e.png
  private/adm/pages/register/upload/teachers/6279b9d166f80.png
  private/adm/pages/register/upload/teachers/627af35643139.png
  private/adm/pages/register/upload/teachers/627c4e7740e0e.png
  private/adm/pages/register/upload/teachers/627c4f2793c31.png
  private/adm/pages/register/upload/teachers/627c6517eef1f.jpg
  private/adm/pages/register/upload/teachers/627d0418a289d.png
  private/adm/pages/register/upload/teachers/627d06021df0c.png
  private/adm/pages/register/upload/teachers/627d061d256a2.png
  private/adm/pages/register/upload/teachers/627d06d041e6e.png
  private/adm/pages/register/upload/teachers/627d07c8e431e.png
  private/adm/pages/register/upload/teachers/627d0a805671b.png
  private/adm/pages/register/upload/teachers/627d4342a87c7.png
  private/adm/pages/register/upload/teachers/627db21473d32.png
  private/style/form-register-teacher.page.css
  private/style/form-update-teacher.style.css
  views/styles/colors.style.css
Labels: CODE REVIEW, Front pronto

#8 Feat/page/login
  views/images/components/seta-voltar.svg
  views/pages/login/css-login/login-style.css
  views/pages/login/css-login/valid-login.css
  views/pages/login/img/fundo2.svg
  views/pages/login/login-page.php
  views/styles/button.style.css
  views/styles/input.style.css
Labels: CODE REVIEW, Front em andamento

#17 feat/update-teacher
  private/adm/pages/register/register-teacher/form-update-teacher.page.php
  private/adm/pages/register/upload/teachers/62669fa6e2f48.png
  private/adm/pages/register/upload/teachers/62669fe178615.png
  private/adm/pages/register/upload/teachers/62669feb29a76.png
  private/adm/pages/register/upload/teachers/62669ff637b6f.png
  private/adm/pages/register/upload/teachers/6266a00d45e3a.png
  private/adm/pages/register/upload/teachers/6266a01a24101.png
  private/adm/pages/register/upload/teachers/6266a02a9a3f1.png
  private/adm/pages/register/upload/teachers/6279b89fc3c4e.png
  private/adm/pages/register/upload/teachers/6279b9d166f80.png
  private/adm/pages/register/upload/teachers/627af35643139.png
  private/adm/pages/register/upload/teachers/627c4e7740e0e.png
  private/adm/pages/register/upload/teachers/627c4f2793c31.png
  private/adm/pages/register/upload/teachers/627c6517eef1f.jpg
  private/adm/pages/register/upload/teachers/627d0418a289d.png
  private/adm/pages/register/upload/teachers/627d06021df0c.png
  private/adm/pages/register/upload/teachers/627d061d256a2.png
  private/adm/pages/register/upload/teachers/627d06d041e6e.png
  private/adm/pages/register/upload/teachers/627d07c8e431e.png
  private/adm/pages/register/upload/teachers/627d0a805671b.png
  private/adm/pages/register/upload/teachers/627d4342a87c7.png
  private/adm/pages/register/upload/teachers/627db21473d32.png
  private/adm/pages/register/upload/teachers/627ee34b29735.png
  private/adm/pages/register/upload/teachers/627ee3a021f82.png
  private/adm/pages/register/upload/teachers/627ee3dd640cb.png
  private/style/form-update-teacher.style.css
Labels: CODE REVIEW, Front pronto

#19 Feat/delete teacher modal
  private/adm/pages/js/delete-teacher.js
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/upload/teachers/627ee34b29735.png
  private/adm/pages/register/upload/teachers/627ee3a021f82.png
  private/adm/pages/register/upload/teachers/627ee3dd640cb.png
  private/style/modal-delete-teacher.style.css
  views/styles/colors.style.css
  views/styles/style.global.css
Labels: CODE REVIEW, Front pronto

#18 Listagem de Professores
  private/adm/images/unit-card-img.svg
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/register-teacher/search-teacher.page.php
  private/adm/pages/register/register.styles.css
  private/adm/pages/register/registration panel/registration-panel-page.php
  private/adm/pages/register/registration panel/registration-panel-style.css
  private/adm/pages/register/upload/teachers/627dadf421a92.jpeg
  private/adm/pages/register/upload/teachers/627fd4aead2e0.jpg
  private/adm/pages/register/upload/teachers/627fda265f64d.jpg
  private/adm/pages/register/upload/teachers/627fe1c507dfe.jpg
  private/adm/pages/register/upload/teachers/627fe1de6bb8a.jpeg
  private/adm/pages/register/upload/teachers/627fe20785c82.jpg
  private/adm/pages/register/upload/teachers/627fe237e7998.jpeg
  private/adm/pages/register/upload/teachers/627fe250048f7.jpeg
  private/adm/pages/register/upload/teachers/627fe25bdf077.jpg
  private/adm/pages/register/upload/teachers/62818928d4027.jpg
  views/images/components/delete-bin.svg
  views/images/components/edit-pen.svg
  views/images/components/search-icon.svg
  views/images/components/three-dots.svg
Labels: CODE REVIEW

#20 Feat/style module registers
  private/adm/pages/js/delete-module.js
  private/adm/pages/js/delete-teacher.js
  private/adm/pages/register/register-module/form-register-module.page.php
  private/adm/pages/register/register-module/form-update-module.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/style/form-update-teacher.style.css
  private/style/modal-delete-teacher.style.css
  views/styles/button.style.css
  views/styles/colors.style.css
Labels: CODE REVIEW, Front pronto

#13 Página de Etecs
  classes/inheritances/Social.class.php
  classes/places/Place.class.php
  classes/schools/School.class.php
  classes/schools/Teacher.class.php
  database/script/help.sql
  database/script/script.txt
  private/adm/images/icons/facebook.svg
  private/adm/images/icons/github.svg
  private/adm/images/icons/instagram.svg
  private/adm/images/icons/linkedin.svg
  private/adm/images/ilustrations/no-image.svg
  private/adm/pages/js/button-filter.js
  private/adm/pages/js/delete-school.js
  private/adm/pages/js/disabled-inputs.js
  private/adm/pages/js/textarea.js
  private/adm/pages/js/visibility-inputs.js
  private/adm/pages/register/register-module/form-register-module.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/controller/delete-school.controller.php
  private/adm/pages/register/register-school/controller/json-school.controller.php
  private/adm/pages/register/register-school/controller/school-unit-registration.controller.php
  private/adm/pages/register/register-school/controller/update-school.controller.php
  private/adm/pages/register/register-school/form-register-school.page.php
  private/adm/pages/register/register-school/form-update-school.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register-teacher/controller/update-teacher.controller.php
  private/adm/pages/register/registration panel/registration-panel-page.php
  private/adm/pages/register/upload/teachers/627dadf421a92.jpeg
  private/adm/pages/register/upload/teachers/627fd4aead2e0.jpg
  private/adm/pages/register/upload/teachers/627fda265f64d.jpg
  private/adm/pages/register/upload/teachers/627fe1c507dfe.jpg
  private/adm/pages/register/upload/teachers/627fe1de6bb8a.jpeg
  private/adm/pages/register/upload/teachers/627fe20785c82.jpg
  private/adm/pages/register/upload/teachers/627fe237e7998.jpeg
  private/adm/pages/register/upload/teachers/627fe250048f7.jpeg
  private/adm/pages/register/upload/teachers/627fe25bdf077.jpg
  private/adm/pages/register/upload/teachers/62818928d4027.jpg
  private/style/style.css
Labels: CODE REVIEW, Back pronto

#26 Página de matérias
  classes/schools/Subject.class.php
  database/script/help.sql
  database/script/script.txt
  private/adm/pages/js/delete-subject.js
  private/adm/pages/register/download/materias.xml
  private/adm/pages/register/register-module/form-update-module.page.php
  private/adm/pages/register/register-subject/controller/delete-subject.controller.php
  private/adm/pages/register/register-subject/controller/subject-batch-resgistration.controller.php
  private/adm/pages/register/register-subject/controller/subject-unit-registration.controller.php
  private/adm/pages/register/register-subject/controller/update-subject.controller.php
  private/adm/pages/register/register-subject/form-batch-registration.subject.controller.php
  private/adm/pages/register/register-subject/form-register-subject.page.php
  private/adm/pages/register/register-subject/form-update-subject.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
  private/adm/pages/register/registration panel/registration-panel-page.php
Labels: CODE REVIEW, Back pronto

#24 Listagem de Módulos
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register.styles.css
Labels: CODE REVIEW

#22 feat/pagination-and-counter-correction
  classes/schools/Module.class.php
  classes/schools/Teacher.class.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-module/search-module.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/register-teacher/search-teacher.page.php
Labels: CODE REVIEW, Back pronto

#25 Página de cursos
  classes/schools/Course.class.php
  classes/schools/Courses.class.php
  classes/schools/Module.class.php
  classes/schools/School.class.php
  classes/schools/Subject.class.php
  classes/schools/Subjects.class.php
  classes/schools/Teacher.class.php
  database/script/help.sql
  database/script/script.txt
  private/adm/pages/js/delete-course.js
  private/adm/pages/js/delete-subject.js
  private/adm/pages/register/download/materias.xml
  private/adm/pages/register/register-course/controller/course-unit-registration.controller.php
  private/adm/pages/register/register-course/controller/delete-course.controller.php
  private/adm/pages/register/register-course/controller/json-course.controller.php
  private/adm/pages/register/register-course/controller/update-course.controller.php
  private/adm/pages/register/register-course/form-register-course.page.php
  private/adm/pages/register/register-course/form-update-course.page.php
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-module/form-update-module.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-subject/controller/delete-subject.controller.php
  private/adm/pages/register/register-subject/controller/subject-batch-resgistration.controller.php
  private/adm/pages/register/register-subject/controller/subject-unit-registration.controller.php
  private/adm/pages/register/register-subject/controller/update-subject.controller.php
  private/adm/pages/register/register-subject/form-batch-registration.subject.controller.php
  private/adm/pages/register/register-subject/form-register-subject.page.php
  private/adm/pages/register/register-subject/form-update-subject.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
  private/adm/pages/register/registration panel/registration-panel-page.php
  private/adm/pages/register/upload/courses/teste copy 4.txt
  private/style/style.css
Labels: CODE REVIEW, Back pronto

#27 Feat/pagination-etecs
  classes/schools/School.class.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
Labels: CODE REVIEW, Back em andamento

#29 Listagem das ETECs
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register.styles.css
  private/adm/pages/register/upload/courses/628c4dab36793.png
  private/adm/pages/register/upload/courses/628c4f4d5d22b.png
  private/adm/pages/register/upload/courses/628d1621e340c.png
  private/adm/pages/register/upload/courses/628d1670797ad.png
  private/adm/pages/register/upload/courses/628d1689d3a47.png
  private/adm/pages/register/upload/schools/628b7fbf8e995.jpg
  private/adm/pages/register/upload/schools/628b82b70de10.png
  private/adm/pages/register/upload/schools/628d0d5c27b81.png
  views/images/components/location-symbol.svg
Labels: CODE REVIEW, Front pronto

#23 ADM Dashboard
  private/adm/images/components/trophy-icon.svg
  private/adm/images/icons/icon-acucar.svg
  private/adm/pages/dashboard/dashboard.page.php
  private/adm/pages/dashboard/style.dashboard.css
  private/adm/pages/dashboard/teste copy 5.txt
  private/adm/pages/register/registration panel/registration-panel-page.php
  private/adm/pages/register/upload/schools/628632f7dcc09.png
  private/adm/pages/register/upload/schools/62863412cb4b7.jpg
  private/adm/pages/register/upload/schools/628795f0c01d5.jpg
  private/adm/pages/register/upload/schools/6287982633823.jpg
  private/adm/pages/register/upload/schools/628799f2dcc32.png
  private/adm/pages/register/upload/schools/62879a6f14be9.png
  private/adm/pages/register/upload/schools/62879af06396d.png
  private/adm/pages/register/upload/schools/62879b96c4f25.png
  private/adm/pages/register/upload/schools/6288593ec2ef3.png
  private/adm/pages/register/upload/schools/62885969bf7f9.png
  private/adm/pages/register/upload/teachers/628436dacc97a.png
  private/adm/pages/register/upload/teachers/628436e36729a.png
  private/adm/pages/register/upload/teachers/628436ea52cbb.png
  private/adm/pages/register/upload/teachers/628436f392d38.png
  private/adm/pages/register/upload/teachers/628436fc2ce4b.png
  private/adm/pages/register/upload/teachers/62843705d731c.png
  private/adm/pages/register/upload/teachers/62843770080d6.png
  private/adm/pages/register/upload/teachers/6284377b4150d.png
  private/adm/pages/register/upload/teachers/62843781c6d27.png
  private/adm/pages/register/upload/teachers/6284378869b4e.png
  private/adm/pages/register/upload/teachers/62843804b3aac.png
  private/adm/pages/register/upload/teachers/6284380cdb52e.png
  private/adm/pages/register/upload/teachers/62879b77e95e7.png
  private/adm/pages/register/upload/teachers/628857ad68387.png
  private/adm/pages/register/upload/teachers/62897e4158a8f.png
  private/adm/pages/register/upload/teachers/62897e4689dbe.png
  views/images/avatars/avatar-scotty.svg
  views/images/background/dashboard/background-help-adm.svg
  views/images/components/filled-dashboard-img.svg
Labels: CODE REVIEW, Front pronto

#35 Fix login page
  views/pages/login/css-login/valid-login.css
  views/pages/login/login-page.php
  views/pages/login/validacao.js
Labels: CODE REVIEW, Front pronto

#31 Listagem de Cursos
  private/adm/pages/register/register-course/list-course.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/register.styles.css
  private/adm/pages/register/registration panel/registration-panel-page.php
  private/adm/pages/register/registration panel/registration-panel-style.css
  private/adm/pages/register/upload/courses/628e40cc1b465.png
  private/adm/pages/register/upload/courses/6291113860512.png
  private/adm/pages/register/upload/schools/628b7fbf8e995.jpg
  private/adm/pages/register/upload/schools/628d0d5c27b81.png
Labels: CODE REVIEW, Front pronto

#34 Renomeação de classe
  classes/schools/School.class.php
  private/adm/pages/register/register-school/list-school.page.php
Labels: CODE REVIEW

#38 Fix painel info
  private/adm/pages/register/registration panel/registration-panel-page.php
Labels: CODE REVIEW

#37 Listagem de Matérias
  private/adm/images/batch-card-img.svg
  private/adm/pages/register/register-subject/list-subject.page.php
  private/adm/pages/register/register.styles.css
Labels: CODE REVIEW, Front pronto

#33 Cadastro do fale conosco: Email e Mensagem
  classes/messages/Message.class.php
  database/script/help.sql
  private/adm/pages/js/textarea.js
  views/landing-page/form-register-message/controller/message-unit-registration.controller.php
  views/landing-page/landing-page-styles.css
  views/landing-page/landing-page.php
Labels: CODE REVIEW, Back pronto

#45 Feat/linkagem pages3
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-school/list-school.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/registration panel/registration-panel-page.php
Labels: CODE REVIEW

#40 Paginação no modal do professor
  classes/schools/School.class.php
  private/adm/pages/js/pagination-teacher-modal.js
  private/adm/pages/register/register-school/controller/pagination-teacher-modal.php
  private/adm/pages/register/register-school/list-school.page.php
Labels: CODE REVIEW, Back pronto

#46 Paginação na página de cursos
  classes/schools/Course.class.php
  private/adm/pages/register/register-course/list-course.page.php
Labels: CODE REVIEW, Back pronto

#44 Paginação na listagem de matérias
  classes/schools/Module.class.php
  classes/schools/Subject.class.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-subject/list-subject.page.php
Labels: CODE REVIEW, Back pronto
