Repository kvlsndkf/project, pull requests merged in 2022-04, with the labels that each got.

#1 Pasta private
  private/teste.txt
Labels: CODE REVIEW

#2 CSS Global
  views/styles/fonts.style.css
  views/styles/fonts/ABCGintoNord-Bold-Trial.otf
  views/styles/fonts/ABCGintoNord-Medium-Trial.otf
  views/styles/fonts/ABCGintoNord-Thin-Trial.otf
  views/styles/fonts/ABCGintoNormal-Bold-Trial.otf
  views/styles/fonts/ABCGintoNormal-Medium-Trial.otf
  views/styles/fonts/ABCGintoNormal-Thin-Trial.otf
  views/styles/fonts/whitneybold.otf
  views/styles/fonts/whitneylight.otf
  views/styles/fonts/whitneymedium.otf
  views/styles/style.global.css
Labels: CODE REVIEW

#4 Database e classes
  classes/denunciations/Denunciation.class.php
  classes/inheritances/Social.class.php
  classes/inheritances/User.class.php
  classes/messages/Message.class.php
  classes/schools/Courses.class.php
  classes/schools/Module.class.php
  classes/schools/School.class.php
  classes/schools/Subjects.class.php
  classes/schools/Teacher.class.php
  classes/solicitations/Solicitation.class.php
  classes/users/Company.class.php
  classes/users/Student.class.php
  database/connection.php
  database/script/help.sql
  database/script/script.txt
Labels: CODE REVIEW

#5 Tela de escolha de perfil (Aluno ou Empresa)
  views/images/avatars/avatar-bento.svg
  views/images/avatars/avatar-bigbird.svg
  views/images/avatars/avatar-bopper.svg
  views/images/avatars/avatar-bouncer.svg
  views/images/avatars/avatar-camie.svg
  views/images/avatars/avatar-cap2.svg
  views/images/avatars/avatar-cap3.svg
  views/images/avatars/avatar-cap4.svg
  views/images/avatars/avatar-capper.svg
  views/images/avatars/avatar-cat.svg
  views/images/avatars/avatar-cherry.svg
  views/images/avatars/avatar-fairy.svg
  views/images/avatars/avatar-froge.svg
  views/images/avatars/avatar-gill.svg
  views/images/avatars/avatar-house.svg
  views/images/avatars/avatar-locke.svg
  views/images/avatars/avatar-nerm.svg
  views/images/avatars/avatar-oslow.svg
  views/images/avatars/avatar-peppe.svg
  views/images/avatars/avatar-worm.svg
  views/images/components/arrow-back.svg
  views/images/favicon/favicon-16x16.png
  views/images/favicon/favicon-32x32.png
  views/images/logo/logo-and-name.svg
  views/images/logo/logo-help.svg
  views/images/logo/logo-name.svg
  views/images/profiles/profile-aluno.svg
  views/images/profiles/profile-empresa-parceira.svg
  views/pages/register/register-profile/register-profile.pages.css
  views/pages/register/register-profile/register-profile.pages.php
  views/pages/register/register-student/register-student.pages.css
  views/pages/register/register-student/register-student.pages.php
  views/styles/colors.style.css
  views/styles/font-format.style.css
Labels: CODE REVIEW

#7 Página professores back-end
  classes/schools/Teacher.class.php
  private/adm/images/teste.txt
  private/adm/pages/dashboard/teste copy 5.txt
  private/adm/pages/js/alert.js
  private/adm/pages/js/autocomplete.js
  private/adm/pages/js/update-teacher.js
  private/adm/pages/register/register-module/teste copy 4.txt
  private/adm/pages/register/register-teacher/controller/delete-teacher.controller.php
  private/adm/pages/register/register-teacher/controller/teacher-unit-registration.controller.php
  private/adm/pages/register/register-teacher/controller/update-teacher.controller.php
  private/adm/pages/register/register-teacher/form-register-teacher.page.php
  private/adm/pages/register/register-teacher/form-update-teacher.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/registration panel/registration-panel.php
  private/adm/pages/register/upload/schools/teste copy 3.txt
  private/adm/pages/register/upload/teachers/teste copy 2.txt
  private/student/teste copy.txt
  private/style/search-bar.style.css
Labels: CODE REVIEW, Back pronto

#9 Página de módulos back end
  classes/schools/Module.class.php
  classes/schools/Teacher.class.php
  private/adm/pages/js/delete-module.js
  private/adm/pages/js/delete-teacher.js
  private/adm/pages/register/register-module/controller/delete-module.controller.php
  private/adm/pages/register/register-module/controller/module-unit-registration.controller.php
  private/adm/pages/register/register-module/controller/update-module.controller.php
  private/adm/pages/register/register-module/form-register-module.page.php
  private/adm/pages/register/register-module/form-update-module.page.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-module/teste copy 4.txt
  private/adm/pages/register/register-teacher/controller/delete-teacher.controller.php
  private/adm/pages/register/register-teacher/controller/update-teacher.controller.php
  private/adm/pages/register/register-teacher/form-register-teacher.page.php
  private/adm/pages/register/register-teacher/form-update-teacher.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
  private/adm/pages/register/registration panel/registration-panel.php
Labels: CODE REVIEW, Back pronto

#11 Ajuste nos contadores das páginas
  classes/schools/Module.class.php
  classes/schools/Teacher.class.php
  private/adm/pages/register/register-module/list-module.page.php
  private/adm/pages/register/register-teacher/list-teacher.page.php
Labels: CODE REVIEW, Back pronto, WAITING
